#!/bin/bash

echo "========================================"
echo "NPU Monitor Quick Start Guide"
echo "========================================"
echo ""
echo "1. Setup:"
echo "   chmod +x setup.sh && ./setup.sh"
echo ""
echo "2. Start monitoring:"
echo "   ./start.sh"
echo "   Note: containers use deploy/mini_init.py as PID 1"
echo "   Recommended cluster entry: deploy/create_agent_container.sh"
echo ""
echo "3. Check status:"
echo "   ./status.sh"
echo "   python3 healthcheck.py"
echo ""
echo "4. Query statistics:"
echo "   python3 query_stats.py --today"
echo "   python3 query_stats.py --month"
echo ""
echo "5. Stop monitoring:"
echo "   ./stop.sh"
echo ""
echo "========================================"
echo "Data Format:"
echo "========================================"
echo "Location: data/daily/stats_YYYY-MM-DD.csv"
echo "Fields:   timestamp, card_id, utilization, hbm_used_mb, hbm_total_mb"
echo "Example:  2026-08-05 14:30:00,0,45.5,1024,65536"
echo ""
echo "========================================"
echo "Calculation Method:"
echo "========================================"
echo "Average = Sum(all utilization) / Count(all samples)"
echo "Same as headquarters probe method"
echo "========================================"
